server:
  servlet:
    context-path: /recite
  port: 8080

spring:
  datasource:
    platform: mysql
    url: jdbc:mysql://localhost:3306/db_recite
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Therion970720!
    type: com.alibaba.druid.pool.DruidDataSource
    data: classpath:data.sql
    druid:
      min-idle: 3
      initial-size: 5
      max-active: 10
      validation-query: select 1
  jpa:
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: update
  redis:
    host: localhost
    port: 6379
